Add Blog Header
jiks-dev/ui-blog pull request #3
Opened 2022-02-13 14:32 UTC by rd-dhyoo

# Description
- 표준 UI Layout 의 Header / Content / Footer 중 Header 의 구성 완료 
- DataProvider 을 이용하여 데이터 분리.
- 이후 DataProvider은 hook 과 같은 state 형태로 데이터를 관리 할 수 있도록 변경방안이 필요.

# Screenshots
![image](https://user-images.githubusercontent.com/71996956/153757828-270edd40-bdf7-4b22-8bc4-4df3021d1f01.png)

2022-02-26 00:51 UTC, karriz-dev commented on src/App.tsx
> +import "./App.css";
상대 경로 말고 절대 경로로 세팅할 수 있는데 이건 코드에서 알려줄 수 없으니 다음 만남때 알려드리겠습니다 😆

2022-02-26 00:58 UTC, karriz-dev requested changes

2022-02-26 00:58 UTC, karriz-dev commented on src/dataProviders/header/SectionProvider.ts
> +const sections = [
타입 스크립트 인것을 활용해 정의해주면 더 좋습니다.
아래 예시를 참조해보세요 

```typescript
interface SectionType = {
  title: String;
  url : String;
};

const sections : SectionType[] = [
  // ...
]
```

**Reference**
https://jess2.xyz/typescript/types-1/

2022-02-26 00:58 UTC, karriz-dev commented on src/dataProviders/header/TitleProvider.ts
> +export function GetHeaderTitle() {
해당 함수도 return 타입을 지정해주시길 바랍니다. (위 reference 블로그 참고)

2022-02-26 00:58 UTC, karriz-dev commented on src/App.tsx
> +import "./App.css";
해당 코멘트는 확인했으면 바로 Resolve 처리 해주시면 됩니다 !

2022-02-26 01:34 UTC, rd-dhyoo commented on src/dataProviders/header/TitleProvider.ts
> +export function GetHeaderTitle() {
![image](https://user-images.githubusercontent.com/71996956/155823694-c0a06319-fc32-4603-816f-516c60bf23a0.png)

2022-02-26 02:09 UTC, MarkYoo23 commented
@karriz-dev 다시 리뷰해주세요~

2022-02-27 10:11 UTC, karriz-dev requested changes

2022-02-27 10:11 UTC, karriz-dev commented on .gitignore
.yarn/ 추가

2022-02-28 13:05 UTC, karriz-dev commented
다음 PR에는 상대경로(../../) 로 되어있는 방식을 절대경로(@.../) 으로 변경해서 올려주세요.

2022-03-08 22:32 UTC, rd-dhyoo commented
@karriz-dev 머지해주세요~

2022-03-18 08:56 UTC, karriz-dev approved these changes

2022-03-18 08:56 UTC, merged